"""init

Revision ID: 108c5046d425
Revises: 
Create Date: 2026-03-28 18:49:13.539956
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108c5046d425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_phone'), 'pacientes', ['phone'], unique=True)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_event_id')
    )
    op.create_index('ix_consultas_doctor_scheduled_at', 'consultas', ['doctor_name', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_consultas_patient_id'), 'consultas', ['patient_id'], unique=False)
    op.create_index('ix_consultas_patient_scheduled_at', 'consultas', ['patient_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_consultas_scheduled_at'), 'consultas', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_consultas_status'), 'consultas', ['status'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_documentos_created_at'), 'documentos', ['created_at'], unique=False)
    op.create_index('ix_documentos_patient_created', 'documentos', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_documentos_patient_id'), 'documentos', ['patient_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_created_at'), 'feedbacks', ['created_at'], unique=False)
    op.create_index('ix_feedbacks_patient_created', 'feedbacks', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_feedbacks_patient_id'), 'feedbacks', ['patient_id'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_created_at'), 'mensagens', ['created_at'], unique=False)
    op.create_index(op.f('ix_mensagens_direction'), 'mensagens', ['direction'], unique=False)
    op.create_index('ix_mensagens_external_channel', 'mensagens', ['external_id', 'channel'], unique=False)
    op.create_index(op.f('ix_mensagens_intent'), 'mensagens', ['intent'], unique=False)
    op.create_index('ix_mensagens_patient_direction_created', 'mensagens', ['patient_id', 'direction', 'created_at'], unique=False)
    op.create_index(op.f('ix_mensagens_patient_id'), 'mensagens', ['patient_id'], unique=False)
    op.create_table('lembretes_enviados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'kind', name='uq_reminder_kind')
    )
    op.create_index(op.f('ix_lembretes_enviados_appointment_id'), 'lembretes_enviados', ['appointment_id'], unique=False)
    op.create_index('ix_lembretes_kind_sent_at', 'lembretes_enviados', ['kind', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lembretes_kind_sent_at', table_name='lembretes_enviados')
    op.drop_index(op.f('ix_lembretes_enviados_appointment_id'), table_name='lembretes_enviados')
    op.drop_table('lembretes_enviados')
    op.drop_index(op.f('ix_mensagens_patient_id'), table_name='mensagens')
    op.drop_index('ix_mensagens_patient_direction_created', table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_intent'), table_name='mensagens')
    op.drop_index('ix_mensagens_external_channel', table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_direction'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_created_at'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_feedbacks_patient_id'), table_name='feedbacks')
    op.drop_index('ix_feedbacks_patient_created', table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_created_at'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_documentos_patient_id'), table_name='documentos')
    op.drop_index('ix_documentos_patient_created', table_name='documentos')
    op.drop_index(op.f('ix_documentos_created_at'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_consultas_status'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_scheduled_at'), table_name='consultas')
    op.drop_index('ix_consultas_patient_scheduled_at', table_name='consultas')
    op.drop_index(op.f('ix_consultas_patient_id'), table_name='consultas')
    op.drop_index('ix_consultas_doctor_scheduled_at', table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_pacientes_phone'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
