"""init

Revision ID: f1beef3b2e5e
Revises: 108c5046d425
Create Date: 2026-03-28 19:06:31.055440
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1beef3b2e5e'
down_revision = '108c5046d425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
